### PR TITLE
Bug Fix: Select-Text RTL styling in kw theme

### LINKED ISSUE #2620: [BUG] Copy component in RTL in plh_kids_kw theme
**Describe the bug**
The copy component in the `plh_kids_kw` theme looks strange when a RTL language is selected.

LTR vs RTL: 
image   image

**App version**
v0.17.0

**Deployment Sheet(s)**
[user_id](https://plh-kids-kw-uat1.web.app/template/user_id)

**Debug Sheet(s)**
[comp_select_text](https://idems-debug.web.app/template/comp_select_text)

### PR DESCRIPTION
**Pull request by FaithDaka**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description
- Support added for RTL for `select-text` component
- Styling fix made for Kuwait theme

## Git Issues

Closes #2620 

## Screenshots
RTL vs LTR

### CODE REVIEW

**Review by esmeetewinkel — APPROVED** [review]
Functional test passed, I can confirm that this closes the issue. 

I did discover an additional issue (both on RTL and LTR): 
The highlighted area when the button is clicked has slightly more rounded corners than the box itself, and therefore doesn't cover the entire white area. 
image    image

@FaithDaka Happy for you to decide whether it makes sense to address that in this PR too or to do as a follow-up PR.

**Review by jfmcquade — APPROVED** [review]
Looks good. @FaithDaka I'll leave it up to you whether you want to merge as-is or address Esmee's issue in this PR.

**Comment by FaithDaka** [comment]
Issues addressed @esmeetewinkel 

LTR vs RTL

**Comment by esmeetewinkel** [comment]
Thanks @FaithDaka, looks great!

**Pull request merged**
