### PR TITLE
Kuwait Theme: Completion modal

### LINKED ISSUE #2540: [FEATURE] Kuwait Theme - Completion Modal
**What?**
Create a module completion component according to the Kuwait theme design.

**Why?**
This modal congratulates a user after they have completed a module and links to a moment of play activity.

**How?**
- [x] Create a module completion component. This component activates after a user clicks the trophy icon and completes the module.
- [x] Declare it within the `index.ts` file within the plh folder
- [x] Create a component sheet with the desired attributes
- [x] Test the component with data from the component sheet

**Other details**

### PR DESCRIPTION
**Pull request by FaithDaka**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description
Styling added for the completion modal page `plh_completion_modal`. [Link](https://docs.google.com/spreadsheets/d/1Uw0QcLJfb2PzvKLSdxXdJojx-zvbUfw12dl-Sy6KrC8/edit?usp=sharing)

## Git Issues

Closes #2540

### CODE REVIEW

**Comment by FaithDaka** [comment]
The modal "image" will be a `.gif`. It was mentioned that we could use Lottie files?
I have a file available for the gift box animation
[Gift-box-animation.json](https://github.com/user-attachments/files/18020681/New-file.json)

**Review by jfmcquade — CHANGES_REQUESTED** [review]
I think ultimately this should be a display group variant rather than a standalone component, but I appreciate that the styling of the background image is quite custom, so I think I'm happy with this being a standalone `plh` component for now.

In line with @esmeetewinkel's comment [here](https://github.com/IDEMSInternational/open-app-builder/issues/2540#issuecomment-2518167943), you're right to not include any modal logic in the pop-up as it will just be displayed within a standard pop-up. Possibly the component name could be changed from "modal", but as it's custom for a specific deployment I don't think that's too important. I do think that it will have to be displayed in a full-screen pop-up, as our non-fullscreen pop-up does not support custom styling like (we would want to apply a gradient going to the very edges of the container and add the background "confetti" image with an offset). So I think displaying this component, with its own rounded corners, within a fullscreen pop-up is probably the best option for now.

I would suggest making the following changes:
- The height of the component should be the full container height rather than a set value, so that it always fills the screen but doesn't 
- The `gift_image_asset` doesn't need to be passed into the component params, it can just be authored in the child template rows, like the title and button
  - This will also enable the use of a lottie animation, via the existing `lottie_animation` component.
  
So essentially this component should be seen as a container with a background gradient applied and background image at the top with an offset, that spans the height of the screen and vertically centres its child rows.

**Comment by FaithDaka** [comment]
@jfmcquade This is the outcome of `height:100%` for the outer div


I think a min-height is still required to achieve the styling

**Comment by FaithDaka** [comment]
Also to note: Setting the `background_image_asset` as the component's `background-image` cuts the top offset off.

**Comment by jfmcquade** [comment]
> I think a min-height is still required to achieve the styling

Yeh, makes sense that you'd need a min-height. Perhaps this should be calculated relative to the viewport height, e.g. `90vh`?

> Also to note: Setting the `background_image_asset` as the component's `background-image` cuts the top offset off.

You're right, so I guess this does need to be passed into an `img` component as you had before.

**Comment by FaithDaka** [comment]
> > I think a min-height is still required to achieve the styling
> 
> Yeh, makes sense that you'd need a min-height. Perhaps this should be calculated relative to the viewport height, e.g. `90vh`?
> 
> > Also to note: Setting the `background_image_asset` as the component's `background-image` cuts the top offset off.
> 
> You're right, so I guess this does need to be passed into an `img` component as you had before.

Changes made @jfmcquade

**Comment by jfmcquade** [comment]
I've updated the styling to make the component taller, and also added negative margins to make it appear better when used within a fullscreen pop-up (the intended use-case). This is a bit of a hack, but this component only has that one specific use-case.

In fullscreen pop-up:
Screenshot 2024-12-06 at 12 59 54

In standalone template:
Screenshot 2024-12-06 at 13 01 28

**Review by jfmcquade — APPROVED** [review]

**Pull request merged**
