### PR TITLE
Kuwait Theme: Styling (Combo-box, Dashed-box, Task Card)

### LINKED ISSUE #2541: [FEATURE] Kuwait Theme - Activity Library components
**What?**
The activity library holds the activities to be used by the parents. Activities get unlocked according to the modules completed and can be filtered by age group or activity state(unlocked, favourite). It also includes a streak count of the number of videos unlocked.

**Why?**
The library provides easy accessibility to the activities for parents.

**How?**
- [x] Activity card component
- [ ] Streak count component
- [ ] Filter component
- [x] Category filter component

**Other details**

### PR DESCRIPTION
**Pull request by FaithDaka**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description
Includes styling of the combo-box, dashed-box and task card component according to design.

One change applied across all themes is that the pop-up launched by the combo-box component now imposes a visible backdrop over the content behind it, making for more consistent UX across the app pop-ups

Screenshot 2024-12-20 at 11 25 32

## Git Issues

Closes #2541 

## Screenshots
| Component | Styling |
|-------------|--------|
| `combo-box` | see video below |
| `dashed-box` |  |
| `task-card` |  |

https://github.com/user-attachments/assets/f335a02a-53fc-4bc4-b591-599a7f31e25e

### CODE REVIEW

**Comment by FaithDaka** [comment]
@esmeetewinkel The `task-card` here was styled according to the `activity-library` page, and the combo-box was styled for user responses in modules

**Review by esmeetewinkel — COMMENTED** [review]
Thanks @FaithDaka, looking good. Happy with the changed combo box and dashed box (I'm not sure if we use the dashed box anywhere in the KW deployments, do we?)

For the task card:
Are you suggesting to use the `block-button` variant for the KW activity buttons? Just checking since they look quite dissimilar, and I'm not sure how to pass in the "favourite" property into the variant. 

image

image

So far I'd been using the "experimental custom content" task card (see [template](https://docs.google.com/spreadsheets/d/1V8iYNvVVc0whiZ3p--ulL_93DiOEH_SKwwwSqLX6OE4/edit?gid=0#gid=0&range=A20) and [preview](https://plh-kids-kw-uat1--pr102-content-1-1-73-5sgmy4e0.web.app/template/activity_library)). Would something like that work?

image

**Comment by FaithDaka** [comment]
@esmeetewinkel The activity cards will use the `portrait` variant. That block-button is a variant for `facilitator_mx` homepage cards.

**Review by jfmcquade — APPROVED** [review]
Looks good, I'm happy to merge.

 Just to flag one change that affects all themes, not just KW, the combo box modal will now have a visible backdrop. @FaithDaka pointed out that this is better UX, so it is sensible to include the change for all themes. I will update the PR description to mention this

**Comment by esmeetewinkel** [comment]
Follow-up issue [here](https://github.com/IDEMSInternational/open-app-builder/issues/2651)

**Pull request merged**
